// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SqlSampleDatabase.UnitTests.Procedures
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Process Order")]
    [NUnit.Framework.CategoryAttribute("debug")]
    public partial class ProcessOrderFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "debug"};
        
#line 1 "ProcessOrder.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Process Order", null, ProgrammingLanguage.CSharp, new string[] {
                        "debug"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Process incoming orders and update orders table with latest order")]
        public virtual void ProcessIncomingOrdersAndUpdateOrdersTableWithLatestOrder()
        {
            string[] tagsOfScenario = ((string[])(null));
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Process incoming orders and update orders table with latest order", null, ((string[])(null)));
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "table name"});
                table1.AddRow(new string[] {
                            "dbo.Orders"});
                table1.AddRow(new string[] {
                            "staging.IncomingOrders"});
#line 5
 testRunner.Given("the following tables on \'SqlSampleDatabase\' are empty:", ((string)(null)), table1, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "OrderId [int]",
                            "CustomerId [nvarchar]",
                            "OrderDate [datetime]",
                            "OrderQuantity [int]"});
                table2.AddRow(new string[] {
                            "5745",
                            "testuser",
                            "2020/07/06 17:59:59",
                            "4"});
#line 9
  testRunner.And("the table \'staging.IncomingOrders\' on \'SqlSampleDatabase\' contains the data:", ((string)(null)), table2, "And ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "ParameterName",
                            "Value",
                            "Type"});
                table3.AddRow(new string[] {
                            "ProcedureName",
                            "ProcessOrder",
                            "nvarchar"});
#line 12
 testRunner.When("the \'proc.ProcessOrder\' stored procedure on \'SqlSampleDatabase\' with params is ex" +
                        "ecuted:", ((string)(null)), table3, "When ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "OrderId [int]",
                            "CustomerId [nvarchar]",
                            "OrderDate [datetime]",
                            "OrderQuantity [int]"});
                table4.AddRow(new string[] {
                            "5745",
                            "Testuser",
                            "2020/07/06 17:59:59",
                            "4"});
#line 15
 testRunner.Then("the table \'dbo.Orders\' on \'SqlSampleDatabase\' should only contain the data withou" +
                        "t strict ordering:", ((string)(null)), table4, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Only process incoming orders and update orders table with latest order if its not" +
            " already processed")]
        public virtual void OnlyProcessIncomingOrdersAndUpdateOrdersTableWithLatestOrderIfItsNotAlreadyProcessed()
        {
            string[] tagsOfScenario = ((string[])(null));
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Only process incoming orders and update orders table with latest order if its not" +
                    " already processed", null, ((string[])(null)));
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "table name"});
                table5.AddRow(new string[] {
                            "dbo.Orders"});
                table5.AddRow(new string[] {
                            "staging.IncomingOrders"});
#line 21
 testRunner.Given("the following tables on \'SqlSampleDatabase\' are empty:", ((string)(null)), table5, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "OrderId [int]",
                            "CustomerId [nvarchar]",
                            "OrderDate [datetime]",
                            "OrderQuantity [int]"});
                table6.AddRow(new string[] {
                            "5745",
                            "testuser",
                            "2020/07/06 17:59:59",
                            "4"});
#line 25
  testRunner.And("the table \'dbo.Orders\' on \'SqlSampleDatabase\' contains the data:", ((string)(null)), table6, "And ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "OrderId [int]",
                            "CustomerId [nvarchar]",
                            "OrderDate [datetime]",
                            "OrderQuantity [int]"});
                table7.AddRow(new string[] {
                            "5745",
                            "testuser",
                            "2020/07/06 17:59:59",
                            "4"});
                table7.AddRow(new string[] {
                            "5755",
                            "testuser",
                            "2020/07/07 18:59:59",
                            "1"});
#line 28
  testRunner.And("the table \'staging.IncomingOrders\' on \'SqlSampleDatabase\' contains the data:", ((string)(null)), table7, "And ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "ParameterName",
                            "Value",
                            "Type"});
                table8.AddRow(new string[] {
                            "ProcedureName",
                            "ProcessOrder",
                            "nvarchar"});
#line 32
 testRunner.When("the \'proc.ProcessOrder\' stored procedure on \'SqlSampleDatabase\' with params is ex" +
                        "ecuted:", ((string)(null)), table8, "When ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "OrderId [int]",
                            "CustomerId [nvarchar]",
                            "OrderDate [datetime]",
                            "OrderQuantity [int]"});
                table9.AddRow(new string[] {
                            "5745",
                            "testuser",
                            "2020/07/06 17:59:59",
                            "4"});
                table9.AddRow(new string[] {
                            "5755",
                            "Testuser",
                            "2020/07/07 18:59:59",
                            "1"});
#line 35
 testRunner.Then("the table \'dbo.Orders\' on \'SqlSampleDatabase\' should only contain the data withou" +
                        "t strict ordering:", ((string)(null)), table9, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
